[theme]
primaryColor = "#c67139"
backgroundColor = "#f9f4ed"
secondaryBackgroundColor = "#eee7db"
textColor = "#201e1d"
linkColor = "#8c491a"
font = "Nunito:https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700&display=swap, sans-serif"
headingFont = "Nunito:https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700&display=swap, sans-serif"
baseFontSize = 15
baseFontWeight = 400
baseRadius = "large"
buttonRadius = "full"
borderColor = "#dcd3c4"
showWidgetBorder = true
showSidebarBorder = false

[theme.sidebar]
backgroundColor = "#f9f4ed"
secondaryBackgroundColor = "#eee7db"
textColor = "#201e1d"
borderColor = "#dcd3c4"

[client]
toolbarMode = "minimal"
